/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.igu.home.admin;

import com.mycompany.igu.Category.CategoryView;
import com.mycompany.igu.Client.ClientAdminView;
import com.mycompany.igu.Login;
import com.mycompany.igu.Main;
import com.mycompany.igu.Product.ProductView;
import com.mycompany.igu.Sale.SaleViewAdmin;
import com.mycompany.igu.Subcategory.SubcategoryView;
import com.mycompany.igu.User.UserViewAdmin;
import com.mycompany.igu.provider.ProviderView;
import com.mycompany.igu.ticket.Ticket;
import com.mycompany.logic.Controller;
import com.mycompany.logic.User;

/**
 *
 * @author Gabriel
 */
public class HomeAdmin extends javax.swing.JFrame {
    Controller controller;
    User user;
    /**
     * Creates new form Home
     */
    public HomeAdmin(Controller controller, User user) {
        initComponents();
        this.controller = controller;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSaleView = new javax.swing.JButton();
        btnCategoryView = new javax.swing.JButton();
        btnProductView = new javax.swing.JButton();
        btnUserView = new javax.swing.JButton();
        btnSubcategoryView = new javax.swing.JButton();
        btnTicketView = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnProviderView = new javax.swing.JButton();
        btnClientView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSaleView.setText("Ventas");
        btnSaleView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleViewActionPerformed(evt);
            }
        });

        btnCategoryView.setText("Category");
        btnCategoryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryViewActionPerformed(evt);
            }
        });

        btnProductView.setText("Productos");
        btnProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductViewActionPerformed(evt);
            }
        });

        btnUserView.setText("Usuarios");
        btnUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserViewActionPerformed(evt);
            }
        });

        btnSubcategoryView.setText("Subcategory");
        btnSubcategoryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubcategoryViewActionPerformed(evt);
            }
        });

        btnTicketView.setText("Ticket");
        btnTicketView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketViewActionPerformed(evt);
            }
        });

        btnLogout.setText("Cerrar Sesion");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnProviderView.setText("Proveedores");
        btnProviderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProviderViewActionPerformed(evt);
            }
        });

        btnClientView.setText("Clientes");
        btnClientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClientView, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(447, 447, 447)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btnTicketView, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSaleView, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProviderView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnProductView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubcategoryView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCategoryView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaleView, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTicketView, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnClientView, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProviderView, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductView, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategoryView, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubcategoryView, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserViewActionPerformed
        // TODO add your handling code here:
        UserViewAdmin userView = new UserViewAdmin(controller, user);
        userView.setVisible(true);
        userView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnUserViewActionPerformed

    private void btnProductViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductViewActionPerformed
        // TODO add your handling code here:
        ProductView pView = new ProductView(controller, user);
        pView.setVisible(true);
        pView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductViewActionPerformed

    private void btnSaleViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleViewActionPerformed
        // TODO add your handling code here:
        SaleViewAdmin sView = new SaleViewAdmin(controller, user);
        sView.setVisible(true);
        sView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSaleViewActionPerformed

    private void btnCategoryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryViewActionPerformed
        // TODO add your handling code here:
        CategoryView cView = new CategoryView(controller, user);
        cView.setVisible(true);
        cView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCategoryViewActionPerformed

    private void btnSubcategoryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubcategoryViewActionPerformed
        // TODO add your handling code here:
        SubcategoryView subCView = new SubcategoryView(controller, user);
        subCView.setVisible(true);
        subCView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSubcategoryViewActionPerformed

    private void btnTicketViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketViewActionPerformed
        // TODO add your handling code here:
        Ticket t = new Ticket(controller, user);
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTicketViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Main login = new Main();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProviderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProviderViewActionPerformed
        // TODO add your handling code here:
        ProviderView pView = new ProviderView(controller, user);
        pView.setVisible(true);
        pView.setLocationRelativeTo(null);
        this.dispose();        
    }//GEN-LAST:event_btnProviderViewActionPerformed

    private void btnClientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientViewActionPerformed
        // TODO add your handling code here:
        ClientAdminView clientView = new ClientAdminView(controller, user);
        clientView.setVisible(true);
        clientView.setLocationRelativeTo(null);
        this.dispose();        

    }//GEN-LAST:event_btnClientViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoryView;
    private javax.swing.JButton btnClientView;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProductView;
    private javax.swing.JButton btnProviderView;
    private javax.swing.JButton btnSaleView;
    private javax.swing.JButton btnSubcategoryView;
    private javax.swing.JButton btnTicketView;
    private javax.swing.JButton btnUserView;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
